version: '3.9'
services:
    app:
        build:
            target: ${APP_ENV:-production}
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-8000}:8000'
        volumes:
            - '.:/app'
        restart: always
